import pygame
from _typeshed import Incomplete
from entities import Entity

class MapObject:
    bat: Incomplete
    gold_zone: Incomplete
    mmap: Incomplete
    texturemap: Incomplete
    solid: Incomplete
    spwan: Incomplete
    content: Incomplete
    jsonconfig: Incomplete
    def __init__(self) -> None: ...
    def attribute_from_coor(self, case_co: tuple[int, int]) -> dict: ...
    def get_bat(self) -> list[Entity]: ...
    def get_texturemap(self) -> list[list[pygame.Surface]]: ...
    def load_file(self, filepath: str) -> None: ...
    def record_info(self, descriptor: str) -> list[str]: ...
    def load_map(self) -> None: ...
    def load_spwan(self) -> None: ...
